/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tinymonster_opencvpicpaste_OpenCVCPP */

#ifndef _Included_com_tinymonster_opencvpicpaste_OpenCVCPP
#define _Included_com_tinymonster_opencvpicpaste_OpenCVCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tinymonster_opencvpicpaste_OpenCVCPP
 * Method:    StitchPanorama
 * Signature: ([Ljava/lang/Object;IJ)I
 */
JNIEXPORT jint JNICALL Java_com_tinymonster_opencvpicpaste_OpenCVCPP_StitchPanorama
  (JNIEnv *, jclass, jobjectArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
